; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.41"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[backup_migrate][version] = "3.1"

projects[better_exposed_filters][version] = "3.2"

projects[ctools][version] = "1.9"

projects[context][version] = "3.6"

projects[facetapi][version] = "1.5"

projects[date][version] = "2.9"

projects[ds][version] = "2.11"

projects[entity][version] = "1.6"

projects[features][version] = "2.6"

projects[flexslider][version] = "2.0-rc1"

projects[fontawesome][version] = "2.1"

projects[formblock][version] = "1.0-alpha1"

projects[globalredirect][version] = "1.5"

projects[google_analytics][version] = "2.1"

projects[imagecache_actions][version] = "1.5"

projects[image_resize_filter][version] = "1.16"

projects[imce][version] = "1.9"

projects[imce_wysiwyg][version] = "1.0"

projects[insert][version] = "1.3"

projects[jcaption][version] = "1.4"

projects[jquery_update][version] = "3.0-alpha2"

projects[libraries][version] = "2.2"

projects[link][version] = "1.3"

projects[masquerade][version] = "1.0-rc7"

projects[menu_icons][version] = "3.0-beta4"

projects[mmenu][version] = "2.1"

projects[oauth][version] = "3.2"

projects[pathauto][version] = "1.2"

projects[pdf_to_imagefield][version] = "3.3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[resource][download][type] = ""
projects[resource][download][url] = ""
projects[resource][type] = "module"
projects[resource][version] = "1.0"

projects[search_api][version] = "1.16"

projects[search_api_db][version] = "1.5"

projects[shrinktheweb][version] = "1.9"

projects[stringoverrides][version] = "1.8"

projects[tagclouds][version] = "1.10"

projects[token][version] = "1.6"

projects[twitter][version] = "5.11"

projects[video_embed_field][version] = "2.0-beta11"

projects[views][version] = "3.11"

projects[views_responsive_grid][version] = "1.3"

projects[wysiwyg][version] = "2.2+63-dev"

; Themes
projects[adaptivetheme][version] = "3.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[urbanarkat][download][type] = ""
projects[urbanarkat][download][url] = ""
projects[urbanarkat][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[mmenu][download][type] = ""
libraries[mmenu][download][url] = ""
libraries[mmenu][directory_name] = "mmenu"
libraries[mmenu][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[flexslider][download][type] = ""
libraries[flexslider][download][url] = ""
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fontawesome][download][type] = ""
libraries[fontawesome][download][url] = ""
libraries[fontawesome][directory_name] = "fontawesome"
libraries[fontawesome][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

